name: Satti
favicon: null
layout_spectrum: 0.9129072
typography_spectrum: 0.4360902
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Profile
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#928665'
    - '#5B5B5C'
    - '#669BE0'
    - '#4B3728'
    - '#FFFFFB'
  brandStrength: 0.6102757
  lightness: 0.4974937
  saturation: 0.5112782
  rhythmicContrast: 0.4761905
purpose: []
