collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.4360902
color:
  saturation: 0.5112782
  brandStrength: 0.6102757
  lightness: 0.4974937
  brandColors:
    - '#928665'
    - '#5B5B5C'
    - '#669BE0'
    - '#4B3728'
    - '#FFFFFB'
  rhythmicContrast: 0.4761905
layout_spectrum: 0.9129072
name: Satti
